### ISSUE TITLE
Crashed on scroll main page

### ISSUE THREAD

**Issue by asimmirza1200** [abh80/smart-edge#24] opened 2022-10-07 03:53 UTC
`[com.abh80.smartedge.activities.MainActivity$ItemDecoration.onDraw(MainActivity.java:261), androidx.recyclerview.widget.RecyclerView.onDraw(RecyclerView.java:4494), android.view.View.draw(View.java:22808), androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429), android.view.View.updateDisplayListIfDirty(View.java:21662), android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588), android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561), android.view.View.updateDisplayListIfDirty(View.java:21619), android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588), android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561), android.view.View.updateDisplayListIfDirty(View.java:21619), android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588), android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561), android.view.View.updateDisplayListIfDirty(View.java:21619), android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588), android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561), android.view.View.updateDisplayListIfDirty(View.java:21619), android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588), android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561), android.view.View.updateDisplayListIfDirty(View.java:21619), android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588), android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561), android.view.View.updateDisplayListIfDirty(View.java:21619), android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588), android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561), android.view.View.updateDisplayListIfDirty(View.java:21619), android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534), android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540), android.view.ThreadedRenderer.draw(ThreadedRenderer.java:620), android.view.ViewRootImpl.draw(ViewRootImpl.java:4743), android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4447), android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3529), android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2305), android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9133), android.view.Choreographer$CallbackRecord.run(Choreographer.java:1232), android.view.Choreographer.doCallbacks(Choreographer.java:1029), android.view.Choreographer.doFrame(Choreographer.java:934), android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217), android.os.Handler.handleCallback(Handler.java:938), android.os.Handler.dispatchMessage(Handler.java:99), android.os.Looper.loopOnce(Looper.java:233), android.os.Looper.loop(Looper.java:344), android.app.ActivityThread.main(ActivityThread.java:8212), java.lang.reflect.Method.invoke(Native Method), com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584), com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)]`

**Comment by asimmirza1200** [comment] 2022-10-07 03:54
View this video

**Comment by asimmirza1200** [comment] 2022-10-07 03:54
View this video 
https://user-images.githubusercontent.com/36633775/194464615-29ad9e0a-ce73-479d-9bc2-200cff4241bb.mp4

**Comment by abh80** [comment] 2022-10-07 08:49
Duplicate of #21

**Closed** 2022-10-07 08:49 UTC
