### ISSUE TITLE
App crashes when attempting to enable plugin

### ISSUE THREAD

**Issue by WovenCoast** [abh80/smart-edge#53] opened 2022-10-13 16:30 UTC
```Error receiving broadcast Intent { act=com.abh80.smartedge.SETTINGS_CHANGED flg=0x10 (has extras) } in com.abh80.smartedge.services.OverlayService$1@d0a9680 : [android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1816), android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2), android.os.Handler.handleCallback(Handler.java:938), android.os.Handler.dispatchMessage(Handler.java:99), android.os.Looper.loopOnce(Looper.java:226), android.os.Looper.loop(Looper.java:313), android.app.ActivityThread.main(ActivityThread.java:8751), java.lang.reflect.Method.invoke(Native Method), com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571), com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)]```

My best guess is something somewhere inside of [onReceive](https://github.com/abh80/smart-edge/blob/master/app/src/main/java/com/abh80/smartedge/services/OverlayService.java#L62) is throwing an error

**Comment by abh80** [comment] 2022-10-14 01:12
Duplicate of #18

**Closed** 2022-10-14 01:12 UTC
